"""init

Revision ID: 0ed592fa16bb
Revises: 
Create Date: 2025-09-19 16:39:11.372420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ed592fa16bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.add_column('lists', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_lists_id'), 'lists', ['id'], unique=False)
    op.drop_column('lists', 'category')
    op.drop_column('lists', 'description')
    op.drop_column('lists', 'title')
    op.drop_column('lists', 'created_at')
    op.drop_column('lists', 'status')
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.ENUM('low', 'medium', 'high'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('tasks', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('low', 'medium', 'high'),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('lists', sa.Column('status', mysql.ENUM('active', 'archived'), nullable=True))
    op.add_column('lists', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('lists', sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('lists', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('lists', sa.Column('category', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_lists_id'), table_name='lists')
    op.drop_column('lists', 'name')
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notify_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'sent'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('notifications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
